[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
state_check_program = "ExuXEXbXpYwNNVrgbMA6qCLruq9NH29zmUfCBrwXmPGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/muhammad/wallet/keypair1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
